#!/bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

# Build the project
yarn build

# # Define a list of pages
# pages="dashboard admin account rumors app4 app5 app6 app7 app8 app9 app10 app11 app12 app13 app14 app15 app16 app17 app18"

# # Iterate over each page and create the directory and copy the index.html file
# for page in $pages
# do
#   mkdir -p "docs/$page"
#   cp "docs/index.html" "docs/$page/index.htm"
# done
